#!/bin/bash

# Install some basic system requirements
sudo apt update
sudo apt install curl fontconfig wget nginx golang-go bash-completion vim unzip -y

# Symlink bashrc
ln -s $HOME/.dotfiles/shell/.bashrc $HOME/.bashrc

# Symlink vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# Symlink fonts
ln -s $HOME/.dotfiles/fonts $HOME/.fonts
ln -s $HOME/.dotfiles/fonts /usr/share/fonts

# Symlink and configure global gitignore
ln -s $HOME/.dotfiles/shell/.gitignore-global $HOME/.gitignore-global
git config --global core.excludesfile $HOME/.gitignore-global
git config --global core.editor "vim"

echo 'Configure font'
echo '--------------'
fc-cache -f -v

echo 'Install NVM'
echo '-----------'
cd $HOME
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
cd $HOME/.dotfiles
echo 'reset the .bashrc file due to changes by the NVM install'
git checkout HEAD -- shell/.bashrc

echo 'Install PHP'
echo '-----------'
sudo apt install php php-dev php-fpm -y

echo 'Install composer'
echo '----------------'
EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi
php composer-setup.php
rm composer-setup.php
sudo mv composer.phar /usr/local/bin/composer
sudo chmod 755 /usr/local/bin/composer

echo 'Install redis'
echo '-------------'
sudo apt install redis -y

echo 'Install Nginx'
echo '-------------'
sudo apt install nginx -y

echo 'Install Mailhog'
echo '---------------'
go get github.com/mailhog/MailHog


echo 'Install Ngrok'
echo '---------------'
cd
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
unzip ngrok-stable-linux-amd64.zip
sudo mv ngrok /usr/local/bin/ngrok
rm ngrok-stable-linux-amd64.zip
sudo chmod 755 /usr/local/bin/ngrok

