#!/bin/bash

# Install some basic system requirements
sudo apt update
sudo apt install curl fontconfig wget nginx bash-completion vim unzip -y

# Symlink bashrc
ln -s $HOME/.dotfiles/shell/.bashrc $HOME/.bashrc

# Symlink vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# Symlink fonts
if [ -d "$HOME/.fonts" ];
then
    rm $HOME/.fonts
fi
ln -s $HOME/.dotfiles/fonts $HOME/.fonts
ln -s $HOME/.dotfiles/fonts /usr/share/fonts

# Symlink and configure global gitignore
ln -s $HOME/.dotfiles/shell/.gitignore-global $HOME/.gitignore-global
git config --global core.excludesfile $HOME/.gitignore-global
git config --global core.editor "vim"

echo 'Configure font'
echo '--------------'
fc-cache -f -v

echo 'Install FNM'
echo '-----------'
cd $HOME
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
cd $HOME/.dotfiles

echo 'Install PHP'
echo '-----------'
sudo apt install php php-dev php-fpm -y

echo 'Install composer'
echo '----------------'
EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi
php composer-setup.php
rm composer-setup.php
sudo mv composer.phar /usr/local/bin/composer
sudo chmod 755 /usr/local/bin/composer

echo 'Install redis'
echo '-------------'
sudo apt install redis -y

echo 'Install Nginx'
echo '-------------'
sudo apt install nginx -y

echo 'Install Mailpit'
echo '---------------'
sudo bash < <(curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh)

echo 'Install Ngrok'
echo '---------------'
cd
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
unzip ngrok-stable-linux-amd64.zip
sudo mv ngrok /usr/local/bin/ngrok
rm ngrok-stable-linux-amd64.zip
sudo chmod 755 /usr/local/bin/ngrok

