#!/bin/bash

# Install some basic system requirements
apt install curl fontconfig php -y

# Symlink bashrc
ln -s $HOME/.dotfiles/shell/.bashrc $HOME/.bashrc

# Symlink vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# Symlink fonts
ln -s $HOME/.dotfiles/fonts $HOME/.fonts
ln -s $HOME/.dotfiles/fonts /usr/share/fonts

# Symlink and configure global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

echo 'Configure font'
echo '--------------'
fc-cache -f -v

echo 'Install NVM'
echo '-----------'
cd $HOME
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
cd $HOME/.dotfiles
echo 'reset the .bashrc file due to changes by the NVM install'
git checkout HEAD -- shell/.bashrc

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer

echo 'Install redis'
echo '-------------'
pecl install redis

